// GENERATED by tools/gen_lte_tbs.ts from 3GPP TS 36.213 (the .docx in 3GPP's zip); do not edit. LTE_TBS_ROWS
// [I_TBS][N_PRB - 1] is the transport block size in bits of table 7.1.7.2.1-1 (I_TBS 0-33, N_PRB 1-110).
//
// Not generated yet: no copy of TS 36.213 was available offline when this was written, and the only
// machine-readable copy on hand is srsRAN's AGPL header, which FieldTap does not copy from. Until the generator has
// run, the table is empty and LteTbsLookup.isAvailable is false: the TBS self-checks and the derived UL MCS are
// not produced, the availability list says why, and the parity tests check the decoders against the reference
// extractor's own table from the git-ignored fixtures.
//
//   deno run -A tools/gen_lte_tbs.ts 36213-h00.docx > src/phy/lteTbsTable.ts

/** The specification the rows were read from ('3GPP TS 36.213 V17.0.0'), empty until generated. */
export const LTE_TBS_SOURCE = '';

export const LTE_TBS_ROWS: readonly (readonly number[])[] = [];
