// Contract v1 parity (ios/Contract/CONTRACT.md): the Swift call flow of each capture, written the way
// Contract/tools/GoldenDump.kt writes the Kotlin one, must equal the golden JSON under GoldenCodec.jsonDiff.
// Also the read-speed check over the real iPhone capture.

import Foundation
import Testing
import FTCore
import FTModel
import FTTestSupport
@testable import FTSignalling

/// A capture read once per test run: its size, records and the counts GoldenDump.kt puts in `source`.
struct QmdlFixture: Sendable {
    var bytes: Int
    var read: DiagProtocol.QmdlRead

    static func load(_ relative: String) -> QmdlFixture? {
        guard let url = Fixtures.url(relative), let data = try? Data(contentsOf: url) else { return nil }
        return QmdlFixture(bytes: data.count, read: DiagProtocol.readQmdl(data))
    }

    static let iphone = load("iphone-recovered.qmdl")
    static let attach4 = load("qdss-attach4/expected/attach4.qmdl")
    static let onePlus5g = load(OnePlus.fiveGPath)
    static let onePlusCallbox = load(OnePlus.callboxPath)

    func flow() -> Flow { CallFlowReader.read(records: read.records, crcErrors: read.crcErrors) }

    /// The flow as callflow-golden.json. `source.file` is ignored by the comparator, so any name will do.
    func golden(_ flow: Flow, file: String) -> Data {
        let source = GoldenSource(file: file, bytes: bytes, hdlcFrames: read.frames, crcErrors: read.crcErrors,
                                  logRecords: read.records.count, badPackets: read.badPackets)
        return GoldenCodec.encodeFlow(flow, source: source, recordsPerCode: read.recordsPerCode)
    }
}

@Suite struct ContractParityTests {
    /// Reads `qmdl`, encodes its flow and compares it with `golden`; returns the Swift flow for further checks.
    @discardableResult
    private func matches(_ fixture: QmdlFixture?, qmdl: String, golden: String,
                         sourceLocation: SourceLocation = #_sourceLocation) -> Flow? {
        guard Fixtures.require(qmdl, sourceLocation: sourceLocation) != nil,
              let expected = Fixtures.require(golden, sourceLocation: sourceLocation) else { return nil }
        guard let fixture else {
            Issue.record("could not read \(qmdl)", sourceLocation: sourceLocation)
            return nil
        }
        let flow = fixture.flow()
        JSONAssert.equal(fixture.golden(flow, file: (qmdl as NSString).lastPathComponent), expected,
                         sourceLocation: sourceLocation)
        return flow
    }

    @Test(.fixture("iphone-recovered.qmdl"), .fixture("contract/callflow-golden.json"))
    func iphoneCallFlowMatchesContract() throws {
        guard let flow = matches(QmdlFixture.iphone, qmdl: "iphone-recovered.qmdl", golden: "contract/callflow-golden.json")
        else { return }
        // The headline numbers of CONTRACT.md, so a golden regenerated by mistake is noticed here too.
        #expect(flow.records == 92_133)
        #expect(flow.events.count == 128)
        #expect(flow.events.count { $0.layer == .RRC && $0.rat == "lte" } == 100)
        #expect(flow.events.count { $0.layer == .RRC && $0.rat == "nr" } == 4)
        #expect(flow.events.count { $0.layer == .NAS } == 24)
        #expect(flow.procedures.count == 34)
        #expect(flow.procedures.allSatisfy { $0.outcome == .SUCCEEDED })
        #expect(flow.journey.map(\.move) == [.FIRST_SEEN, .RESELECTION, .HANDOVER, .HANDOVER])
        #expect(flow.connections.map(\.outcome) == [.RELEASED, .OPEN_AT_END])
        #expect(flow.cellDetails.count == 3)
        #expect(flow.undecoded == 5)
        #expect(abs(flow.durationMs - 26_959.395) < 0.001)
        #expect(flow.startUtcMs == 1_790_019_725_984)
        // The reader's D1 pass and TimeBase.of (what the Analyzer and FTPhy use) agree on the same records.
        let timeBase = TimeBase.of(try #require(QmdlFixture.iphone).read.records)
        #expect(flow.durationMs == timeBase.durationMs)
        #expect(flow.startUtcMs == timeBase.startUtcMs)
        // D4: event 73 is an NR message logged before the SCG cell was assigned.
        #expect(flow.events[73].cell?.isPendingNr == true)
        // The masked golden really hides what the Swift flow decoded: identity fields exist before masking.
        let masked = flow.events.flatMap(\.fields).map { Redaction.mask($0) }
        #expect(masked.contains { $0.value == Redaction.masked || $0.children.contains { $0.value == Redaction.masked } })
    }

    @Test(.fixture("qdss-attach4/expected/attach4.qmdl"), .fixture("contract/callflow-attach4.json"))
    func attach4MatchesContract() {
        guard let flow = matches(QmdlFixture.attach4, qmdl: "qdss-attach4/expected/attach4.qmdl",
                                 golden: "contract/callflow-attach4.json") else { return }
        #expect(flow.records == 2_351)
        #expect(flow.events.count == 33)
        #expect(flow.procedures.count == 7)
    }

    @Test(.fixture(OnePlus.fiveGPath), .fixture("contract/oneplus-5g-registration.json"))
    func onePlus5gMatchesContract() {
        guard let flow = matches(QmdlFixture.onePlus5g, qmdl: OnePlus.fiveGPath,
                                 golden: "contract/oneplus-5g-registration.json") else { return }
        #expect(flow.records == 18)
        #expect(flow.events.count == 11)
        #expect(flow.procedures.count == 2)
        #expect(flow.journey.count == 2)
        // Repo main's time base on this capture, kept by D1 because every stamp is plausible.
        #expect(abs(flow.durationMs - -99_494.492) < 0.001)
    }

    @Test(.fixture(OnePlus.callboxPath), .fixture("contract/oneplus-callbox-service-request.json"))
    func onePlusCallboxMatchesContract() {
        guard let flow = matches(QmdlFixture.onePlusCallbox, qmdl: OnePlus.callboxPath,
                                 golden: "contract/oneplus-callbox-service-request.json") else { return }
        #expect(flow.records == 26)
        #expect(flow.events.count == 18)
        #expect(flow.procedures.count == 7)
    }

    /// The Kotlin JVM reference reads this capture in 294-322 ms; the Swift port must stay under a second in a
    /// release build (test-kit.sh --release). Debug builds on a Mac shared with other builds vary tenfold between
    /// runs, so there the bound only catches an accidental quadratic.
    @Test(.fixture("iphone-recovered.qmdl"))
    func performanceOfReadOverTheRealCapture() throws {
        guard Fixtures.require("iphone-recovered.qmdl") != nil else { return }
        let fixture = try #require(QmdlFixture.iphone)
        let records = fixture.read.records
        #expect(records.count == 92_133)
        let clock = ContinuousClock()
        var runs: [Duration] = []
        var events = 0
        for _ in 0..<3 {
            let started = clock.now
            let flow = CallFlowReader.read(records: records, crcErrors: fixture.read.crcErrors)
            runs.append(clock.now - started)
            events = flow.events.count
        }
        let median = runs.sorted()[1]
        let ms = Double(median.components.seconds) * 1_000 + Double(median.components.attoseconds) / 1e15
        print("FTSignalling performance: CallFlowReader.read over \(records.count) records, median of 3 = \(Fmt.fixed(ms, 1)) ms "
            + "(runs \(runs.map { Fmt.fixed(Double($0.components.attoseconds) / 1e15 + Double($0.components.seconds) * 1_000, 1) }))")
        #expect(events == 128)
        #if DEBUG
        let limit = Duration.seconds(5)
        #else
        let limit = Duration.seconds(1)
        #endif
        #expect(median < limit, "median \(Fmt.fixed(ms, 1)) ms")
    }
}
