"""Render wireshark/fieldtap.lua, the Wireshark plugin that decodes "fieldtap-diag" frames.

The plugin is checked in, so a user copies one file into Wireshark's plugins folder.
It is rendered from here so that its log-code names come from the same register the
decoder uses (registry.LOG_CODES); a test fails when the checked-in file is stale.

    python -m fieldtap.wireshark_plugin            # rewrite wireshark/fieldtap.lua
    python -m fieldtap.wireshark_plugin --check    # exit 1 when it differs

The per-code field decoders live in wireshark/fieldtap_lte.lua and fieldtap_nr.lua,
written by hand to mirror the Python decoders; a tshark test checks the two agree on
the same frames. This file only owns the core: the frame header, the code table, and
the hook the per-code files register into.
"""

from __future__ import annotations

import os
import sys

from .decode.registry import LOG_CODES

PLUGIN_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "wireshark")
CORE_PATH = os.path.join(PLUGIN_DIR, "fieldtap.lua")

_TEMPLATE = r'''-- FieldTap: Wireshark plugin for the "fieldtap-diag" exported PDU.
--
-- GENERATED by `python -m fieldtap.wireshark_plugin` from fieldtap/decode/registry.py.
-- Edit the template in fieldtap/wireshark_plugin.py, not this file.
--
-- Install: copy fieldtap.lua, fieldtap_lte.lua and fieldtap_nr.lua into Wireshark's
-- personal plugins folder (Help > About Wireshark > Folders > Personal Lua Plugins),
-- or run tshark with -X lua_script:fieldtap.lua -X lua_script:fieldtap_lte.lua ...
--
-- A FieldTap capture carries RRC and NAS as native PDUs; every other diag log record
-- arrives in this wrapper. Without the plugin the bytes are still in the file; with it
-- each record shows its log code, name, modem timestamp and, for the layouts FieldTap
-- knows, its fields. Files are load-order independent: each one creates the shared
-- table if it does not exist yet.

FieldTap = FieldTap or { decoders = {}, names = {}, confidence = {} }

-- log code -> name, from the register
%(names)s

-- log code -> layout confidence, from the register ("high", "medium", "low")
%(confidence)s

local proto = Proto("fieldtap-diag", "FieldTap diag log record")

local f_magic   = ProtoField.string("fieldtap.magic", "Magic")
local f_format  = ProtoField.uint8("fieldtap.format", "Format")
local f_code    = ProtoField.uint16("fieldtap.code", "Log code", base.HEX)
local f_name    = ProtoField.string("fieldtap.name", "Log name")
local f_flags   = ProtoField.uint8("fieldtap.flags", "Flags", base.HEX)
local f_ts_ok   = ProtoField.bool("fieldtap.timestamp_plausible", "Modem timestamp plausible", 8, nil, 0x01)
local f_decoded = ProtoField.bool("fieldtap.decoded_by_fieldtap", "Decoded by FieldTap", 8, nil, 0x02)
local f_ts_raw  = ProtoField.uint64("fieldtap.timestamp_raw", "Modem timestamp (raw)", base.HEX)
local f_ts      = ProtoField.absolute_time("fieldtap.timestamp", "Modem timestamp", base.UTC)
local f_len     = ProtoField.uint16("fieldtap.body_len", "Body length")
local f_body    = ProtoField.bytes("fieldtap.body", "Record body")
local f_version = ProtoField.uint32("fieldtap.version", "Packet version")
local f_layout  = ProtoField.string("fieldtap.layout", "Layout")

proto.fields = { f_magic, f_format, f_code, f_name, f_flags, f_ts_ok, f_decoded, f_ts_raw, f_ts, f_len,
                 f_body, f_version, f_layout }

-- Qualcomm log timestamp (CDMA system time): the high 48 bits count 1.25 ms ticks
-- from the GPS epoch (1980-01-06 00:00:00 UTC, no leap seconds); the low 16 bits are
-- 1/32-chip units at 1.2288 Mcps. The same arithmetic as fieldtap/diag/protocol.py.
local GPS_EPOCH = 315964800
local TICK_SECONDS = 1.25 / 1000
local FRACTION_HZ = 1.2288e6 * 32
local function qc_time(raw)
  local ticks = raw:rshift(16):tonumber()
  local frac = raw:band(0xFFFF):tonumber()
  local seconds = ticks * TICK_SECONDS + frac / FRACTION_HZ
  local whole = math.floor(seconds)
  return NSTime.new(GPS_EPOCH + whole, math.floor((seconds - whole) * 1e9))
end

-- Shared helpers for the per-code decoders (fieldtap_lte.lua, fieldtap_nr.lua).
FieldTap.helpers = FieldTap.helpers or {}
local H = FieldTap.helpers

-- bits N..N+W-1 (LSB first) of a 32-bit little-endian word at offset off
function H.word_bits(buf, off, skip, width)
  local w = buf(off, 4):le_uint()
  return (math.floor(w / 2 ^ skip)) %% (2 ^ width)
end
function H.rsrp(raw) return raw * 0.0625 - 180 end     -- dBm
function H.rsrq(raw) return raw * 0.0625 - 30 end      -- dB
function H.rssi(raw) return raw * 0.0625 - 110 end     -- dBm
function H.snr(raw) return raw * 0.1 - 20 end          -- dB
-- NR ML1 Q7 fixed point (major.minor 2.7+): 0 means "not available"
function H.nr_q7(raw)
  if raw == 0 then return nil end
  local integer = math.floor(raw / 128) %% 256
  local frac = raw %% 128
  return (integer - 256) + frac * 0.0078125
end
function H.fmt(v, unit, digits)
  if v == nil then return "n/a" end
  return string.format("%%." .. (digits or 1) .. "f %%s", v, unit or "")
end

function proto.dissector(buf, pinfo, tree)
  if buf:len() < 18 or buf(0, 4):string() ~= "FTDG" then return 0 end
  pinfo.cols.protocol = "FieldTap"
  local root = tree:add(proto, buf())
  local code = buf(5, 2):le_uint()
  local flags = buf(7, 1):uint()
  local ts_raw = buf(8, 8):le_uint64()
  local length = buf(16, 2):le_uint()
  local name = FieldTap.names[code] or string.format("unknown log 0x%%04X", code)
  root:add(f_magic, buf(0, 4))
  root:add(f_format, buf(4, 1))
  root:add_le(f_code, buf(5, 2))
  root:add(f_name, buf(5, 2), name)
  local fl = root:add(f_flags, buf(7, 1))
  fl:add(f_ts_ok, buf(7, 1))
  fl:add(f_decoded, buf(7, 1))
  root:add_le(f_ts_raw, buf(8, 8))
  if flags %% 2 == 1 then root:add(f_ts, buf(8, 8), qc_time(ts_raw)) end
  root:add_le(f_len, buf(16, 2))
  local body = buf(18, length)
  root:add(f_body, body)
  root:append_text(string.format(": 0x%%04X %%s", code, name))

  local info = string.format("0x%%04X %%s", code, name)
  local decoder = FieldTap.decoders[code]
  if decoder ~= nil then
    local ok, summary = pcall(decoder, body:tvb(), pinfo, root, { code = code, name = name,
      version_field = f_version, layout_field = f_layout, confidence = FieldTap.confidence[code] })
    if ok and summary ~= nil and summary ~= "" then
      info = info .. " · " .. summary
    elseif not ok then
      root:add_expert_info(PI_MALFORMED, PI_WARN, "FieldTap decoder error: " .. tostring(summary))
      info = info .. " · (layout did not fit; raw bytes kept)"
    end
  else
    info = info .. " · " .. tostring(length) .. " bytes, no layout"
  end
  pinfo.cols.info = info
  return buf:len()
end

-- Nothing else to register: exported_pdu hands a frame to the dissector named in its
-- proto-name tag, and creating the Proto under that name is what makes the match
-- (verified on Wireshark 4.0.1).
'''


def _lua_table(name: str, rows: list) -> str:
    lines = ["%s = {" % name]
    for key, value in rows:
        lines.append("  [0x%04X] = %s," % (key, value))
    lines.append("}")
    return "\n".join(lines)


def render() -> str:
    names = _lua_table("FieldTap.names", [(c, '"%s"' % i.name.replace('"', "'")) for c, i in sorted(LOG_CODES.items())])
    confidence = _lua_table("FieldTap.confidence", [(c, '"%s"' % i.confidence) for c, i in sorted(LOG_CODES.items())])
    return _TEMPLATE % {"names": names, "confidence": confidence}


def write(path: str = CORE_PATH) -> str:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    text = render()
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    return path


def is_current(path: str = CORE_PATH) -> bool:
    try:
        with open(path, encoding="utf-8", newline="") as fh:
            return fh.read().replace("\r\n", "\n") == render()
    except OSError:
        return False


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if "--check" in argv:
        if is_current():
            return 0
        print("wireshark/fieldtap.lua is stale: run python -m fieldtap.wireshark_plugin", file=sys.stderr)
        return 1
    print(write())
    return 0


if __name__ == "__main__":
    sys.exit(main())
