// GENERATED by Tests/FTPhyTests/TestData/tools/gen_lte_tbs.py from 3GPP TS 36.213 (the .docx in 3GPP's zip);
// do not edit. rows[I_TBS][N_PRB - 1] is the transport block size in bits of table 7.1.7.2.1-1 (I_TBS 0-33,
// N_PRB 1-110).
//
// Not generated yet: no copy of TS 36.213 was available offline when FTPhy was written, and the only
// machine-readable copy on hand is srsRAN's AGPL header, which FieldTap does not copy from. Until the generator
// has run, `LteTbs.isAvailable` is false: the TBS self-checks and the derived UL MCS say "not run", and the parity
// tests check the decoders with the reference extractor's own table from the git-ignored Fixtures/local.

enum LteTbsTable {
    /// The specification the rows were read from.
    static let source = ""

    static let rows: [[Int32]] = []
}
