-- FieldTap: Wireshark plugin for the "fieldtap-diag" exported PDU.
--
-- GENERATED by `python -m fieldtap.wireshark_plugin` from fieldtap/decode/registry.py.
-- Edit the template in fieldtap/wireshark_plugin.py, not this file.
--
-- Install: copy fieldtap.lua, fieldtap_lte.lua and fieldtap_nr.lua into Wireshark's
-- personal plugins folder (Help > About Wireshark > Folders > Personal Lua Plugins),
-- or run tshark with -X lua_script:fieldtap.lua -X lua_script:fieldtap_lte.lua ...
--
-- A FieldTap capture carries RRC and NAS as native PDUs; every other diag log record
-- arrives in this wrapper. Without the plugin the bytes are still in the file; with it
-- each record shows its log code, name, modem timestamp and, for the layouts FieldTap
-- knows, its fields. Files are load-order independent: each one creates the shared
-- table if it does not exist yet.

FieldTap = FieldTap or { decoders = {}, names = {}, confidence = {} }

-- log code -> name, from the register
FieldTap.names = {
  [0xB061] = "LTE MAC RACH Trigger",
  [0xB062] = "LTE MAC RACH Attempt",
  [0xB063] = "LTE MAC DL Transport Block",
  [0xB064] = "LTE MAC UL Transport Block",
  [0xB0C0] = "LTE RRC OTA Packet",
  [0xB0C1] = "LTE RRC MIB Message Log Packet",
  [0xB0C2] = "LTE RRC Serving Cell Info Log Packet",
  [0xB0C3] = "LTE RRC PLMN Search Info",
  [0xB0C4] = "LTE RRC PLMN Search Request",
  [0xB0E0] = "LTE NAS ESM Security Protected Incoming Msg",
  [0xB0E1] = "LTE NAS ESM Security Protected Outgoing Msg",
  [0xB0E2] = "LTE NAS ESM Plain OTA Incoming Msg",
  [0xB0E3] = "LTE NAS ESM Plain OTA Outgoing Msg",
  [0xB0E4] = "LTE NAS ESM Bearer Context State",
  [0xB0E5] = "LTE NAS ESM Bearer Context Info",
  [0xB0EA] = "LTE NAS EMM Security Protected Incoming Msg",
  [0xB0EB] = "LTE NAS EMM Security Protected Outgoing Msg",
  [0xB0EC] = "LTE NAS EMM Plain OTA Incoming Msg",
  [0xB0ED] = "LTE NAS EMM Plain OTA Outgoing Msg",
  [0xB0EE] = "LTE NAS EMM State",
  [0xB0EF] = "LTE NAS EMM USIM Card Mode",
  [0xB139] = "LTE PHY PUSCH Tx Report",
  [0xB14D] = "LTE PHY PUCCH CSF",
  [0xB14E] = "LTE PHY PUSCH CSF",
  [0xB16B] = "LTE PHY PDCCH-PHICH Indication Report",
  [0xB173] = "LTE PDSCH Stat Indication",
  [0xB179] = "LTE ML1 Connected Mode LTE Intra-Freq Meas Results",
  [0xB17F] = "LTE ML1 Serving Cell Meas and Eval",
  [0xB180] = "LTE ML1 Idle Neighbor Meas Results",
  [0xB193] = "LTE ML1 Serving Cell Measurement Result",
  [0xB195] = "LTE ML1 Connected Neighbor Meas Request/Response",
  [0xB800] = "NR NAS SM5G Plain OTA Incoming Msg",
  [0xB801] = "NR NAS SM5G Plain OTA Outgoing Msg",
  [0xB808] = "NR NAS SM5G Security Protected Incoming Msg",
  [0xB809] = "NR NAS SM5G Security Protected Outgoing Msg",
  [0xB80A] = "NR NAS MM5G Plain OTA Incoming Msg",
  [0xB80B] = "NR NAS MM5G Plain OTA Outgoing Msg",
  [0xB80C] = "NR NAS MM5G State",
  [0xB80D] = "NR NAS MM5G Security Protected Outgoing Msg",
  [0xB80E] = "NR NAS MM5G (unconfirmed)",
  [0xB80F] = "NR NAS MM5G Service Request",
  [0xB814] = "NR NAS SM5G State",
  [0xB821] = "NR RRC OTA Packet",
  [0xB822] = "NR RRC MIB Info",
  [0xB823] = "NR RRC Serving Cell Info",
  [0xB825] = "NR RRC Configuration Info",
  [0xB826] = "NR5G RRC Supported CA Combos",
  [0xB872] = "NR L2 UL Transport Block",
  [0xB883] = "NR MAC UL Physical Channel Schedule Report",
  [0xB887] = "NR MAC PDSCH Info",
  [0xB888] = "NR MAC PDSCH Stats",
  [0xB88A] = "NR MAC RACH Attempt",
  [0xB975] = "NR ML1 Serving Cell Beam Management",
  [0xB97F] = "NR ML1 Searcher Measurement DB Update Ext",
}

-- log code -> layout confidence, from the register ("high", "medium", "low")
FieldTap.confidence = {
  [0xB061] = "low",
  [0xB062] = "low",
  [0xB063] = "high",
  [0xB064] = "high",
  [0xB0C0] = "high",
  [0xB0C1] = "high",
  [0xB0C2] = "medium",
  [0xB0C3] = "low",
  [0xB0C4] = "low",
  [0xB0E0] = "medium",
  [0xB0E1] = "medium",
  [0xB0E2] = "high",
  [0xB0E3] = "high",
  [0xB0E4] = "low",
  [0xB0E5] = "low",
  [0xB0EA] = "medium",
  [0xB0EB] = "medium",
  [0xB0EC] = "high",
  [0xB0ED] = "high",
  [0xB0EE] = "low",
  [0xB0EF] = "low",
  [0xB139] = "medium",
  [0xB14D] = "low",
  [0xB14E] = "low",
  [0xB16B] = "low",
  [0xB173] = "medium",
  [0xB179] = "medium",
  [0xB17F] = "low",
  [0xB180] = "low",
  [0xB193] = "medium",
  [0xB195] = "low",
  [0xB800] = "medium",
  [0xB801] = "medium",
  [0xB808] = "low",
  [0xB809] = "low",
  [0xB80A] = "medium",
  [0xB80B] = "medium",
  [0xB80C] = "low",
  [0xB80D] = "low",
  [0xB80E] = "low",
  [0xB80F] = "low",
  [0xB814] = "low",
  [0xB821] = "medium",
  [0xB822] = "medium",
  [0xB823] = "medium",
  [0xB825] = "low",
  [0xB826] = "low",
  [0xB872] = "low",
  [0xB883] = "low",
  [0xB887] = "low",
  [0xB888] = "low",
  [0xB88A] = "low",
  [0xB975] = "medium",
  [0xB97F] = "medium",
}

local proto = Proto("fieldtap-diag", "FieldTap diag log record")

local f_magic   = ProtoField.string("fieldtap.magic", "Magic")
local f_format  = ProtoField.uint8("fieldtap.format", "Format")
local f_code    = ProtoField.uint16("fieldtap.code", "Log code", base.HEX)
local f_name    = ProtoField.string("fieldtap.name", "Log name")
local f_flags   = ProtoField.uint8("fieldtap.flags", "Flags", base.HEX)
local f_ts_ok   = ProtoField.bool("fieldtap.timestamp_plausible", "Modem timestamp plausible", 8, nil, 0x01)
local f_decoded = ProtoField.bool("fieldtap.decoded_by_fieldtap", "Decoded by FieldTap", 8, nil, 0x02)
local f_ts_raw  = ProtoField.uint64("fieldtap.timestamp_raw", "Modem timestamp (raw)", base.HEX)
local f_ts      = ProtoField.absolute_time("fieldtap.timestamp", "Modem timestamp", base.UTC)
local f_len     = ProtoField.uint16("fieldtap.body_len", "Body length")
local f_body    = ProtoField.bytes("fieldtap.body", "Record body")
local f_version = ProtoField.uint32("fieldtap.version", "Packet version")
local f_layout  = ProtoField.string("fieldtap.layout", "Layout")

proto.fields = { f_magic, f_format, f_code, f_name, f_flags, f_ts_ok, f_decoded, f_ts_raw, f_ts, f_len,
                 f_body, f_version, f_layout }

-- Qualcomm log timestamp (CDMA system time): the high 48 bits count 1.25 ms ticks
-- from the GPS epoch (1980-01-06 00:00:00 UTC, no leap seconds); the low 16 bits are
-- 1/32-chip units at 1.2288 Mcps. The same arithmetic as fieldtap/diag/protocol.py.
local GPS_EPOCH = 315964800
local TICK_SECONDS = 1.25 / 1000
local FRACTION_HZ = 1.2288e6 * 32
local function qc_time(raw)
  local ticks = raw:rshift(16):tonumber()
  local frac = raw:band(0xFFFF):tonumber()
  local seconds = ticks * TICK_SECONDS + frac / FRACTION_HZ
  local whole = math.floor(seconds)
  return NSTime.new(GPS_EPOCH + whole, math.floor((seconds - whole) * 1e9))
end

-- Shared helpers for the per-code decoders (fieldtap_lte.lua, fieldtap_nr.lua).
FieldTap.helpers = FieldTap.helpers or {}
local H = FieldTap.helpers

-- bits N..N+W-1 (LSB first) of a 32-bit little-endian word at offset off
function H.word_bits(buf, off, skip, width)
  local w = buf(off, 4):le_uint()
  return (math.floor(w / 2 ^ skip)) % (2 ^ width)
end
function H.rsrp(raw) return raw * 0.0625 - 180 end     -- dBm
function H.rsrq(raw) return raw * 0.0625 - 30 end      -- dB
function H.rssi(raw) return raw * 0.0625 - 110 end     -- dBm
function H.snr(raw) return raw * 0.1 - 20 end          -- dB
-- NR ML1 Q7 fixed point (major.minor 2.7+): 0 means "not available"
function H.nr_q7(raw)
  if raw == 0 then return nil end
  local integer = math.floor(raw / 128) % 256
  local frac = raw % 128
  return (integer - 256) + frac * 0.0078125
end
function H.fmt(v, unit, digits)
  if v == nil then return "n/a" end
  return string.format("%." .. (digits or 1) .. "f %s", v, unit or "")
end

function proto.dissector(buf, pinfo, tree)
  if buf:len() < 18 or buf(0, 4):string() ~= "FTDG" then return 0 end
  pinfo.cols.protocol = "FieldTap"
  local root = tree:add(proto, buf())
  local code = buf(5, 2):le_uint()
  local flags = buf(7, 1):uint()
  local ts_raw = buf(8, 8):le_uint64()
  local length = buf(16, 2):le_uint()
  local name = FieldTap.names[code] or string.format("unknown log 0x%04X", code)
  root:add(f_magic, buf(0, 4))
  root:add(f_format, buf(4, 1))
  root:add_le(f_code, buf(5, 2))
  root:add(f_name, buf(5, 2), name)
  local fl = root:add(f_flags, buf(7, 1))
  fl:add(f_ts_ok, buf(7, 1))
  fl:add(f_decoded, buf(7, 1))
  root:add_le(f_ts_raw, buf(8, 8))
  if flags % 2 == 1 then root:add(f_ts, buf(8, 8), qc_time(ts_raw)) end
  root:add_le(f_len, buf(16, 2))
  local body = buf(18, length)
  root:add(f_body, body)
  root:append_text(string.format(": 0x%04X %s", code, name))

  local info = string.format("0x%04X %s", code, name)
  local decoder = FieldTap.decoders[code]
  if decoder ~= nil then
    local ok, summary = pcall(decoder, body:tvb(), pinfo, root, { code = code, name = name,
      version_field = f_version, layout_field = f_layout, confidence = FieldTap.confidence[code] })
    if ok and summary ~= nil and summary ~= "" then
      info = info .. " · " .. summary
    elseif not ok then
      root:add_expert_info(PI_MALFORMED, PI_WARN, "FieldTap decoder error: " .. tostring(summary))
      info = info .. " · (layout did not fit; raw bytes kept)"
    end
  else
    info = info .. " · " .. tostring(length) .. " bytes, no layout"
  end
  pinfo.cols.info = info
  return buf:len()
end

-- Nothing else to register: exported_pdu hands a frame to the dissector named in its
-- proto-name tag, and creating the Proto under that name is what makes the match
-- (verified on Wireshark 4.0.1).
