#!/usr/bin/env python3
"""Generates FieldTapKit/Sources/FTPhy/LteTbsTable.swift from 3GPP TS 36.213 itself.

Input: the specification's .docx, as 3GPP publishes it (https://www.3gpp.org/ftp/Specs/archive/36_series/36.213/,
e.g. 36213-h00.zip -> 36213-h00.docx; any release from 12 on has the 34 x 110 table). Only the standard library
is used: the .docx is a zip of WordprocessingML, and table 7.1.7.2.1-1 is read from the tables that follow its
caption, up to the next table caption. Nothing is taken from any other implementation's copy of the table.

  gen_lte_tbs.py 36213-h00.docx > FieldTapKit/Sources/FTPhy/LteTbsTable.swift
  gen_lte_tbs.py --self-test

Checks before writing: 34 (or 27, pre-Rel-12) rows of 110 sizes; every size is a multiple of 8 whose TB+CRC
segments into turbo code blocks without filler (TS 36.212 5.1.2); sizes never shrink as N_PRB grows from 2 on.
"""
import io, re, sys, zipfile
import xml.etree.ElementTree as ET

W = '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}'
CAPTION = re.compile(r'Table\s+7\.1\.7\.2\.1-1\b')
NEXT_CAPTION = re.compile(r'^\s*Table\s+\d')


def text(el):
    return ''.join(t.text or '' for t in el.iter(W + 't')).strip()


def rows_after_caption(document_xml):
    """The cell texts of every table row between the 7.1.7.2.1-1 caption and the next table caption."""
    body = ET.fromstring(document_xml).find(W + 'body')
    inside, rows = False, []
    for el in body:
        if el.tag == W + 'p':
            t = text(el)
            if CAPTION.search(t):
                inside = True
            elif inside and NEXT_CAPTION.match(t):
                break
        elif el.tag == W + 'tbl' and inside:
            for tr in el.iter(W + 'tr'):
                rows.append([text(tc) for tc in tr.findall(W + 'tc')])
    return rows


def integer(s):
    s = s.replace(' ', '').replace(' ', '')
    return int(s) if re.fullmatch(r'\d+', s) else None


def parse(rows):
    """{(i_tbs, n_prb): tbs} from header rows (consecutive N_PRB numbers) and data rows (I_TBS, sizes...)."""
    table, columns = {}, None
    for cells in rows:
        nums = [integer(c) for c in cells]
        tail = [n for n in nums[1:] if n is not None]
        consecutive = len(tail) >= 2 and all(b == a + 1 for a, b in zip(tail, tail[1:]))
        if consecutive and (nums[0] is None or len(tail) >= 5) and len(tail) == len(cells) - 1:
            columns = tail
            continue
        if columns and nums[0] is not None and all(n is not None for n in nums[1:]) and len(nums) - 1 == len(columns):
            for n_prb, size in zip(columns, nums[1:]):
                table[(nums[0], n_prb)] = size
    return table


INTERLEAVER = set(range(40, 513, 8)) | set(range(528, 1025, 16)) | set(range(1056, 2049, 32)) | set(range(2112, 6145, 64))


def segments_cleanly(tbs):
    """TS 36.212 5.1.2: TB + 24-bit CRC, split into C blocks each with its own CRC, all of one interleaver size."""
    if tbs % 8:
        return False
    b = tbs + 24
    if b <= 6144:
        return b in INTERLEAVER
    c = -(-b // 6120)
    return (b + 24 * c) % c == 0 and (b + 24 * c) // c in INTERLEAVER


def grid(table, validate=True):
    n_rows = max(i for i, _ in table) + 1
    rows = [[table.get((i, n)) for n in range(1, 111)] for i in range(n_rows)]
    problems = []
    if n_rows not in (27, 34):
        problems.append('%d I_TBS rows (expected 34, or 27 before Rel-12)' % n_rows)
    for i, row in enumerate(rows):
        if None in row:
            problems.append('I_TBS %d: N_PRB %s missing' % (i, [n + 1 for n, v in enumerate(row) if v is None][:5]))
            continue
        if validate:
            bad = [v for v in row if not segments_cleanly(v)]
            if bad:
                problems.append('I_TBS %d: sizes %s do not segment cleanly' % (i, bad[:5]))
            # From N_PRB 2 on: the published table has one known oddity in its first column (I_TBS 6, N_PRB 1).
            if any(b < a for a, b in zip(row[1:], row[2:])):
                problems.append('I_TBS %d: a size shrinks as N_PRB grows' % i)
    if problems:
        sys.exit('gen_lte_tbs: ' + '; '.join(problems))
    return rows


def swift(rows, source):
    out = ['// GENERATED by Tests/FTPhyTests/TestData/tools/gen_lte_tbs.py from 3GPP TS 36.213 (%s); do not edit.' % source,
           '// rows[I_TBS][N_PRB - 1] is the transport block size in bits of table 7.1.7.2.1-1 (I_TBS 0-%d, N_PRB 1-110).'
           % (len(rows) - 1), '', 'enum LteTbsTable {', '    /// The specification the rows were read from.',
           '    static let source = "%s"' % source, '', '    static let rows: [[Int32]] = [']
    for i, row in enumerate(rows):
        out.append('        // I_TBS %d' % i)
        for k in range(0, 110, 12):
            out.append('        ' + ('[' if k == 0 else ' ') + ', '.join(str(v) for v in row[k:k + 12])
                       + ('],' if k + 12 >= 110 else ','))
    out += ['    ]', '}', '']
    return '\n'.join(out)


def read_docx(path):
    with zipfile.ZipFile(path) as z:
        return z.read('word/document.xml')


def self_test():
    """A synthetic document laid out like the specification: caption, blocks of 10 N_PRB columns, next caption."""
    sizes = sorted(t for t in range(16, 400_000, 8) if segments_cleanly(t))
    def p(t):
        return '<w:p><w:r><w:t>%s</w:t></w:r></w:p>' % t
    def tr(cells):
        return '<w:tr>' + ''.join('<w:tc><w:p><w:r><w:t>%s</w:t></w:r></w:p></w:tc>' % c for c in cells) + '</w:tr>'
    blocks = []
    for k in range(0, 110, 10):
        rows = [tr(['I', 'N']), tr([''] + [str(n + 1) for n in range(k, k + 10)])]
        rows += [tr([str(i)] + [str(sizes[i * 3 + n]) for n in range(k, k + 10)]) for i in range(34)]
        blocks.append('<w:tbl>' + ''.join(rows) + '</w:tbl>')
    xml = ('<w:document xmlns:w="%s"><w:body>' % W[1:-1] + p('Table 7.1.7.1-1: other') + '<w:tbl>' + tr(['0', '99'])
           + '</w:tbl>' + p('Table 7.1.7.2.1-1: Transport block size table (dimension 34x110)') + ''.join(blocks)
           + p('Table 7.1.7.2.2-1: One-layer to two-layer TBS translation table') + '<w:tbl>' + tr(['1', '2'])
           + '</w:tbl></w:body></w:document>').encode()
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w') as z:
        z.writestr('word/document.xml', xml)
    rows = grid(parse(rows_after_caption(read_docx(io.BytesIO(buf.getvalue())))))
    assert len(rows) == 34 and all(len(r) == 110 for r in rows)
    assert rows[5][17] == sizes[5 * 3 + 17] and rows[33][109] == sizes[33 * 3 + 109]
    assert 'static let rows' in swift(rows, 'self-test')
    print('gen_lte_tbs self-test: 34 x 110 parsed from 11 column blocks, validity checks pass')


if __name__ == '__main__':
    if sys.argv[1:] == ['--self-test']:
        self_test()
    elif len(sys.argv) == 2:
        rows = grid(parse(rows_after_caption(read_docx(sys.argv[1]))))
        sys.stdout.write(swift(rows, re.sub(r'\.docx$', '', sys.argv[1].split('/')[-1])))
    else:
        sys.exit(__doc__)
